### ISSUE TITLE
"Conditional" actions running on all PRs

### ISSUE THREAD

**Issue by bnb** [nodejs/examples#33]
Theoretically, both [cli-yargs-countentriesindirectory.yaml](https://github.com/nodejs/examples/blob/main/.github/workflows/cli-yargs-countentriesindirectory.yaml) and [servers-express-api-with-express-and-handlebars.yaml](https://github.com/nodejs/examples/blob/main/.github/workflows/servers-express-api-with-express-and-handlebars.yaml) should only be running on PRs against their respective projects because of this YAML (this specific example is from the GitHub Action for Express's YAML):

```yaml
on:
  push:
    paths:
      - 'servers/express/api-with-express-and-handlebars/**'
  pull_request:
    paths:
      - 'servers/express/api-with-express-and-handlebars/**'
```

According to the [GitHub Actions Documentation](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths), this should work (example from the docs):
```
on:
  push:
    paths:
    - '**.js'
```

I can't tell if I'm missing something or if this feature of GitHub Actions CI is broken, and I honestly can't tell what next steps are to figure that out. That said, with how this project is structured we either need to answer that and find a fix _or_ change how we do CI.
